name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [14]
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - node: 12
            os: ubuntu-latest
          # Fix Node 16 version to 16.2.0
          # 16.3.0 is causing an issue with mock-fs library
          # causing some unit tests in cauldron API to fail
          # This is a temporary solution while waiting for
          # this issue to be addressed by Node team in a new
          # release and/or mock-fs library
          # Reference : https://github.com/tschaub/mock-fs/issues/332
          - node: 16.2.0
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn
      - run: yarn build
      - run: yarn test:unit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: yarn
      - run: yarn check:lint
